# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '**.s'
      - '**.sh'
      - '**/Makefile'
  pull_request:
    branches: [ master ]
  release:
    types: [published, created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [ gcc, clang ]
        exclude: 
          - os: windows-latest
            cc: clang
            
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: build
      env:
        CC: ${{ matrix.cc }}
        CI: gh
      run: make
    - name: archive sources
      if: success()
      run: 7z a ${{ matrix.os }}-${{ matrix.cc }}-${{ github.ref }}.7z .
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: target
        path: ./${{ matrix.os }}-${{ matrix.cc }}-${{ github.ref }}.7z

