# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '**.s'
      - '**.sh'
      - '**/Makefile'
  pull_request:
    branches: [ master ]
  release:
    types: [published, created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [ gcc, clang ]
        exclude:
          - os: windows-latest
            cc: clang

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: install clang
      if: runner.os == 'Windows' && matrix.cc == 'clang'
      run: choco install -y llvm make
      shell: powershell
    - name: build
      env:
        CC: ${{ matrix.cc }}
        CI: gh
      run: make
      shell: powershell
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.cc }}-${{ github.run_id }}
        path: .
    - uses: actions/download-artifact@v1
      if: github.event == 'release' && success()
      with:
        name: ${{ matrix.os }}-${{ matrix.cc }}-${{ github.run_id }}
    - name: Upload to release
      if: github.event == 'release' && success()
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${{ matrix.os }}-${{ matrix.cc }}-${{ github.run_id }}
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
